// Param example below:
// search?hl=en
// &as_q=all+these
// &as_epq="this+exact"
// &as_oq=any+of+these
// &as_eq=noneofthese
// &as_nlo=10
// &as_nhi=100
// &lr=lang_en
// &cr=countryUS
// &as_qdr=w
// &as_sitesearch=http%3A%2F%2Fnewyorktimes.com
// &as_occt=body
// &safe=active
// &as_filetype=pdf
// &as_rights=%28cc_publicdomain%7Ccc_attribute%7Ccc_sharealike%7Ccc_noncommercial%7Ccc_nonderived%29

const queryParams = {
  //  white space between multiple terms, serves as OR methodology and spaces between multiple terms (treated the same)
  multiTerm: '&as_q=' + {multiTermInput1} + '+' + {multiTermInput2},
  exactMatch: '&as-epq=' + '"' + {exactMatchInput} + '"',
  anyOfThese: '&as_oq=' + {anyOfThese1} + 'OR' + {anyOfThese2},
  noneOfThese: '&as_eq' + '-' + {noneOfTheseInput},
  ranges: {
    rangeLo: '&as_nlo=' + {rangeHiInput},
    rangeHi: '&as_nhi=' + {rangeLoInput},
    unitsOfMeasure: {
      lb: this.rangeHi + '+lb',
      //  would need to add additional objects for other currencies
      rangeLoDollar: '%24+' + this.rangeLo,
      rangeHiDollar:'%24+' + this.rangeHi,
    }
  },
  languages: {
    langQuery: '&lr=lang_' + {langSelection},
    languageOptions: {
      'Afrikaans': 'af',
      'Arabic': 'ar',
      'Armenian':'hy',
      'Belarusian': 'be',
      'Bulgarian': 'bg',
      'Croatian': 'hr',
      'Czech': 'cs',
      'Danish': 'da',
      'Dutch': 'nl',
      'English': 'en',
      'Esperanto': 'eo',
      'Estonian': 'et',
      'Filipino': 'tl',
      'Finnish': 'fi',
      'French': 'fr',
      'German': 'de',
      'Greek': 'el',
      'Hebrew': 'iw',
      'Hungarian': 'hu',
      'Icelandic': 'is',
      'Indonesian': 'id',
      'Italian': 'it',
      'Japanese': 'ja',
      'Korean': 'ko',
      'Latvian': 'lv',
      'Lithuanian': 'lt',
      'Norwegian': 'no',
      'Persian': 'fa',
      'Polish': 'pl',
      'Portuguese': 'pt',
      'Romanian': 'ro',
      'Russian': 'ru',
      'Serbian': 'sr',
      'Slovak': 'sk',
      'Slovenian': 'sl',
      'Spanish': 'es',
      'Swedish': 'sv',
      'Thai': 'th',
      'Turkish': 'tr',
      'Ukrainian': 'uk',
      'Vietnamese': 'vi',
      'Chinese Simplified': 'zh-CN',
      'Chinese Traditional': 'zh-TW',
    }
  },
  regions: {
    regionQuery: '&cr=country' + {regionSelectionInput},
    regionList: {
        'Afghanistan': 'AF',
        'Albania': 'AL',
        'Algeria': 'DZ',
        'AmericanSamoa': 'AS',
        'Andora': 'AD',
        'Angola': 'AO',
        'Anguilla': 'AI',
        'Antarctica': 'AQ',
        'Antigua and Barbuda': 'AG',
        'Argentina': 'AR',
        'Armenia': 'AM',
        'Aruba': 'AW',
        'Australia': 'AU',
        'Austria': 'AT',
        'Azerbaijan': 'AZ',
        'Bahamas': 'BS',
        'Bahrain': 'BH',
        'Bangladesh': 'BD',
        'Barbados': 'BB',
        'Belarus': 'BY',
        'Belgium': 'BE',
        'Belize': 'BZ',
        'Benin': 'BJ',
        'Bermuda': 'BM',
        'Bhutan': 'BT',
        'Bolivia': 'BO',
        'Bosnia and Herzegovina': 'BA',
        'Botswana': 'BW',
        'Bouvet Island': 'BV',
        'Brazil': 'BR',
        'British Indian Ocean Territory': 'IO',
        'Brunei Darussalam': 'BN',
        'Bulgari': 'BG',
        'Burkina Faso': 'BF',
        'Burundi': 'BI',
        'Cambodia': 'KH',
        'Cameroon': 'CM',
        'Canada': 'CA',
        'Cape Verde': 'CV',
        'Cayman Islands': 'KY',
        'Central African Republic': 'CF',
        'Chad': 'TD',
        'Chile': 'CL',
        'China': 'CN',
        'Christmas Island': 'CX',
        'Cocos (Keeling) Islands': 'CC',
        'Colombia': 'CO',
        'Comoros': 'KM',
        'Congo': 'CG',
        'Congo Democratic Republic' : 'CD',
        'CookIslands': 'CK',
        'Costa Rica':'CR',
        "Cote d'Ivoire": 'CI',
        'Croatia': 'HR',
        'Cyprus': 'CY',
        'Czech Republic': 'CZ',
        'Denmark': 'DK',
        'Djibouti': 'DJ',
        'Dominica': 'DM',
        'Dominican Republic': 'DO',
        'East Timor': 'TL',
        'Ecuador': 'EC',
        'Egypt': 'EG',
        'El Salvador': 'SV',
        'Equatorial Guinea': 'GQ',
        'Eritrea': 'ER',
        'Estonia': 'EE',
        'Ethiopia': 'ET',
        'Falkl and Islands Malvinas': 'FK',
        'Faroe Islands': 'FO',
        'Fiji': 'FJ',
        'Finland': 'FI',
        'France': 'FR',
        'French Guiana': 'GF',
        'French Polynesia': 'PF',
        'French Southern Territories': 'TF',
        'Gabon': 'GA',
        'Gambia': 'GM',
        'Georgia': 'GE',
        'Germany': 'DE',
        'Ghana': 'GH',
        'Gibraltar': 'GI',
        'Greece': 'GR',
        'Greenland': 'GL',
        'Grenada': 'GD',
        'Guadeloupe': 'GP',
        'Guam': 'GU',
        'Guatemala': 'GT',
        'Guinea': 'GN',
        'Guinea Bissau': 'GW',
        'Guyana': 'GY',
        'Haiti': 'HT',
        'Heard and McDonald Islands': 'HM',
        'Honduras': 'HN',
        'Hong Kong': 'HK',
        'Hungary': 'HU',
        'Iceland': 'IS',
        'India': 'IN',
        'Indonesia': 'ID',
        'Iraq': 'IQ',
        'Ireland': 'IE',
        'Israel': 'IL',
        'Italy': 'IT',
        'Jamaica': 'JM',
        'Japan': 'JP',
        'Jordan': 'JO',
        'Kazakhstan': 'KZ',
        'Kenya': 'KE',
        'Kiribati': 'KI',
        'Kuwait': 'KW',
        'Kyrgyzstan': 'KG',
        "LaoPeople's Democratic Republic": 'LA',
        'Latvia': 'LV',
        'Lebanon': 'LB',
        'Lesotho': 'LS',
        'Liberia': 'LR',
        'Libya': 'LY',
        'Liechtenstein': 'LI',
        'Lithuania': 'LT',
        'Luxembourg': 'LU',
        'Macau': 'MO',
        'Macedonia': 'MK',
        'Madagascar': 'MG',
        'Malawi': 'MW',
        'Malaysia': 'MY',
        'Maldives': 'MV',
        'Mali': 'ML',
        'Malta': 'MT',
        'Marshall Islands': 'MH',
        'Martinique': 'MQ',
        'Mauritania': 'MR',
        'Mauritius': 'MU',
        'Mayotte': 'YT',
        'Mexico': 'MX',
        'Micronesia': 'FM',
        'Moldova': 'MD',
        'Monaco': 'MC',
        'Mongolia': 'MN',
        'Montserrat': 'MS',
        'Morocco': 'MA',
        'Mozambique': 'MZ',
        'Namibia': 'NA',
        'Nauru': 'NR',
        'Nepal': 'NP',
        'Netherlands': 'NL',
        'Netherlands Antilles': 'AN',
        'NewCaledonia': 'NC',
        'New Zealand': 'NZ',
        'Nicaragua': 'NI',
        'Niger': 'NE',
        'Nigeria': 'NG',
        'Niue': 'NU',
        'Norfolk Island': 'NF',
        'Northern Maria a Islands': 'MP',
        'Norway': 'NO',
        'Oman': 'OM',
        'Pakistan': 'PK',
        'Palau': 'PW',
        'Palestinian Territory': 'PS',
        'Panama': 'PA',
        'Papua New Guinea': 'PG',
        'Paraguay': 'PY',
        'Peru': 'PE',
        'Philippines': 'PH',
        'Pitcairn': 'PN',
        'Poland': 'PL',
        'Portugal': 'PT',
        'Puerto Rico': 'PR',
        'Qatar': 'QA',
        'Reunion': 'RE',
        'Romania': 'RO',
        'Russian Federation': 'RU',
        'Rwanda': 'RW',
        'Saint Kitts and Nevis': 'KN',
        'Saint Lucia': 'LC',
        'Saint Vincent and the Grenadines': 'VC',
        'Samoa': 'WS',
        'San Marino': 'SM',
        'Sao Tome and Principe': 'ST',
        'Saudi Arabia': 'SA',
        'Senegal': 'SN',
        'Serbia and Montenegro': 'CS',
        'Seychelles': 'SC',
        'Sierra Leone': 'SL',
        'Singapore': 'SG',
        'Slovakia': 'SK',
        'Slovenia': 'SI',
        'Solomon Islands': 'SB',
        'Somalia': 'SO',
        'South Africa': 'ZA',
        'South Georgia and the South Sandwich Islands': 'GS',
        'SouthKorea': 'KR',
        'Spain': 'ES',
        'SriLanka': 'LK',
        'St.Helena': 'SH',
        'St. Pierre and Miquelon': 'PM',
        'Suriname': 'SR',
        'Svalbard and Jan Mayen Islands': 'SJ',
        'Swaziland': 'SZ',
        'Sweden': 'SE',
        'Switzerland': 'CH',
        'Taiwan': 'TW',
        'Tajikistan': 'TJ',
        'Tanzania': 'TZ',
        'Thailand': 'TH',
        'Togo': 'TG',
        'Tokelau': 'TK',
        'Tonga': 'TO',
        'Trinidad and Tobago': 'TT',
        'Tunisia': 'TN',
        'Turkey': 'TR',
        'Turkmenistan': 'TM',
        'Turks and Caicos Islands': 'TC',
        'Tuvalu': 'TV',
        'Uganda': 'UG',
        'Ukraine': 'UA',
        'United Arab Emirates': 'AE',
       ' United Kingdom': 'GB',
       ' United States': 'US',
        'United States Minor Outlying Islands': 'UM',
        'Uruguay': 'UY',
        'Uzbekistan': 'UZ',
        'Vanuatu': 'VU',
        'Vatican': 'VA',
        'Venezuela': 'VE',
        'Viet Nam': 'VN',
        'Virgin Islands British': 'VG',
       ' Virgin Islands U.S.': 'VI',
        'Wallis and Futuna Islands': 'WF',
       ' Western Sahara': 'EH',
        'Yemen': 'YE',
        'Zambia': 'ZM',
        'Zimbabwe': 'ZW'
    }
  },
  lastUpdated: {
    query: '&as_qdr=' + {lastUpdatedInput},
    lastUpdatedOptions: {
      anytime: 'all',
      twentyfourHr: 'd',
      week: 'w',
      month: 'm',
      months: 'm' + {numberOfMonthsInput},
      year: 'y'
    }
  },
  // method required to convert : and / from https --- : = %3A    / = %2F
  searchSiteorDomain: '&as_sitesearch=' + {siteOrDomainInput},
  termsAppearHere: {
    query: 'as_occt=' + {termsAppearHereSelection},
    appearHereOptions: {
      anywhere: 'any',
      title: 'title',
      text: 'body',
      url: 'url',
      links: 'links'
    }
  },
  safesearch: {
    query: '&safe=' + {safeSearchSelection},
    safeSearchOptions: {
      //  note that images will still be filtered even with the limited setting
      on: 'active',
      limited: 'images'
    }
  },
  fileTypes: {
    query: '&as_filetype=' + 'fileTypeSelection',
    fileTypeOptions: {
      'All filetypes': 'any',
      'Adobe Acrobat PDF': 'pdf',
      'Adobe Postscript': 'ps',
      'Autodesk DWF': 'dwf',
      'Google Earth KML': 'kml',
      'Google Earth KMZ': 'kmz',
      'Microsoft Excel': 'xls',
      'Microsoft Powerpoint': 'ppt',
      'Microsoft Word': 'doc',
      'Rich Text Format': 'rtf',
      'Shockwave Flash': 'swf'
    }
  },
  usageRights: {
    query: '&as_rights=' + {usageRightsSelection},
    usageRightsOptions: {
      'not filtered by License': '',
      'free to use or share': '%28cc_publicdomain%7Ccc_attribute%7Ccc_sharealike%7Ccc_noncommercial%7Ccc_nonderived%29',
      'free to use or share, even commercially': '%28cc_publicdomain%7Ccc_attribute%7Ccc_sharealike%7Ccc_nonderived%29.-%28cc_noncommercial%29',
      'free to use, share or modify': '%28cc_publicdomain%7Ccc_attribute%7Ccc_sharealike%7Ccc_noncommercial%29.-%28cc_nonderived%29',
      'free to use, share or modify, even commercially': '%28cc_publicdomain%7Ccc_attribute%7Ccc_sharealike%29.-%28cc_noncommercial%7Ccc_nonderived%29'
    }
  }
}